# Generated by Django 3.2 on 2021-04-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('artist', models.CharField(blank=True, max_length=30, null=True)),
                ('album', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'spotify',
                'ordering': ['genre'],
            },
        ),
    ]
